### ISSUE TITLE
Assertion failed

### ISSUE THREAD

**Issue by slowkow** [deweylab/RSEM#10]
I've encountered a bug when running `rsem-calculate-expression`. If I use the
`--no-bam-output` option, then I it completes without any errors. I believe
this means that my input files must be correct.

However, if I use the `--output-genome-bam` option, then I always get a crash
with output as follows. I snipped out paths to my files because they are
irrelevant to this issue.

```
ROUND = 7130, SUM = 1294266, bChange = 0.00101067, totNum = 1
ROUND = 7131, SUM = 1294266, bChange = 0.00101067, totNum = 1
ROUND = 7132, SUM = 1294266, bChange = 0.00101067, totNum = 1
ROUND = 7133, SUM = 1294266, bChange = 0.00101067, totNum = 1
ROUND = 7134, SUM = 1294266, bChange = 0.000966455, totNum = 0
rsem-run-em: BamWriter.h:135: void BamWriter::work(HitWrapper<PairedEndHit>): Assertion `transcripts.getInternalSid(b->core.tid + 1) == hit->getSid()' failed.
Expression Results are written!
"rsem-run-em <SNIP>" failed! Plase check if you provide correct parameters/options for the pipeline!
```

Do you have any clues or tips? I don't have time to investigate this
error myself.

I ran `rsem-calculate-expression` like this (variables are not relevant for
this issue, since I ran successfully without `--output-genome-bam`):

```
opt=(
    --paired-end
    --num-threads 4
    --bowtie2
    --bowtie2-path $HOME/src/bowtie2-2.2.2
    --bowtie2-k 25
    --phred33-quals
    --output-genome-bam
    --calc-pme
    --estimate-rspd
    --samtools-sort-mem 3G
    --temporary-folder $tmp/rsem
    --time
    $fq1
    $fq2
    $RAM/hg19
    $out/$library
)
rsem-calculate-expression ${opt[*]}
```

Thanks for the excellent software! I'm very pleased with the way you've written
documentation and with the capabilities of the tools you provide.

**Comment by bli25wisc** [comment]
Hi Adrian and slowkow,

Do you still have these assertion errors using the latest RSEM version (v1.2.28)?

Thanks,
Bo

**Comment by adrianveres** [comment]
Hi Bo, I haven't used RSEM since that issue so I won't be able to help
unfortunately. Thank you for checking in!
Adrian

**Comment by bli25wisc** [comment]
Hi Adrian,

Thanks for letting me know this. Can you know if you switch to other tools such as Cufflinks, eXpress, Sailfish/Salmon, Kallisto, or you just switch your project?

Thanks,
Bo

**Comment by adrianveres** [comment]
Hi Bo,
Yes I've been using kallisto for my needs now.
Adrian
