### ISSUE TITLE
rsem-calculate-expression error 

### ISSUE THREAD

**Issue by qwangmsk** [deweylab/RSEM#14]
Hi RSEM expert:

When running this command: "rsem-calculate-expression --bam --estimate-rspd   --no-bam-output  --paired-end Aligned.toTranscriptome.out.bam ./rsem-out Quant", I received an error (see error message below). I wonder what rsem-out.grp is? Could you please give me a hint how to fix it?

Many thanks,
Qingguo

rsem-parse-alignments ./rsem-out Quant.temp/Quant Quant.stat/Quant b Aligned.toTranscriptome.out.bam -t 3 -tag XM
Cannot open ./rsem-out.grp! It may not exist.
"rsem-parse-alignments ./rsem-out Quant.temp/Quant Quant.stat/Quant b Aligned.toTranscriptome.out.bam -t 3 -tag XM" failed! Plase check if you provide correct parameters/options for the pipeline!

**Comment by mbernste** [comment]
Hi,  I'm not an expert of the RSEM package, but I have run into this problem before.  Instead of pointing to the reference "./rsem-out", change it to "./rsem-out/RSEMref".  It seems that the the calculate-expression program expects "RSEMref" to be appended to the reference's prefix.  That fixed it for me.

Matt

**Comment by qwangmsk** [comment]
Hi Matt, this fixed this error! Thanks for your kind help.  

Qingguo

**Comment by reedliu** [comment]
Hi I met this problem with rsem-parse-alignments, can you give me some advice? Thanks!

**rsem-parse-alignments /home/u1239/workspace/rna-seq/Quantification/../Assembly/trinity_out_dir/Trinity.fasta.RSEM RSEM.temp/RSEM RSEM.stat/RSEM bowtie2.bam 3 -tag XM
open: No such file or directory
Cannot open 3! It may not exist.
"rsem-parse-alignments /home/u1239/workspace/rna-seq/Quantification/../Assembly/trinity_out_dir/Trinity.fasta.RSEM RSEM.temp/RSEM RSEM.stat/RSEM bowtie2.bam 3 -tag XM" failed! Plase check if you provide correct parameters/options for the pipeline!
Error, cmd: rsem-calculate-expression  --paired-end   -p 24    --no-bam-output --bam bowtie2.bam /home/u1239/workspace/rna-seq/Quantification/../Assembly/trinity_out_dir/Trinity.fasta.RSEM RSEM  died with ret: 65280 at /home/u1239/Biosoft/Trinity-v2.5.1/util/align_and_estimate_abundance.pl line 778.**

**Comment by mroodgar** [comment]
Hi there, 
I am trying to run "rsem-prepare-reference" suing the otions below:
rsem-prepare-reference --gtf /PATH_to_gtf_file.gtf --star --star-path /PATH_to STAR -p 8 /PATH_to_Genome.fa ./RSEMref

But I get error below:

**"rsem-extract-reference-transcripts ./RSEMref 0 /PATH_to_gtf_file.gtf None 0 /PATH_to_Genome.fa" failed! Plase check if you provide correct parameters/options for the pipeline!**

Has anyone faced the same error or know how to fix this?

Thanks,

Morteza
