### ISSUE TITLE
Which RSEM output should be used: FPKM vs pme_FPKM

### ISSUE THREAD

**Issue by qwangmsk** [deweylab/RSEM#15]
Hi there,

I am using RSEM to calculate gene expression levels (absolute instead of differential expression) in RNA-seq samples. In the output of RSEM, I don't know how posterior mean estimate, e.g. pme_FPKM and pme_TPM, is calculated. To quantify gene expressions in my case, I wonder which you would suggest to use: FPKM (TPM) or pme_FPKM (pme_TPM)? 

Another question is: is it necessary to run quartile normalization on RSEM's output?

Thanks,
Qingguo

**Comment by bli25wisc** [comment]
It depends on your application. If you want to compare a same gene between samples, you need to do some type of normalization, which I suggest the median normalization proposed by DESeq. If you want to compare genes within a sample, you do not need normalization.

The posterior mean estimates are calculated using the Collapsed Gibbs sampler implemented as part of RSEM. For details, please refer to our BMC Bioinformatics paper http://bmcbioinformatics.biomedcentral.com/articles/10.1186/1471-2105-12-323

Based on inputs from ENCODE, it seems the pme_TPM works best for within sample comparison.


Hope it helps,
Bo
