### ISSUE TITLE
IsoPct

### ISSUE THREAD

**Issue by mhjiang97** [deweylab/RSEM#154]
Hi,

I'd like to know how the column `IsoPct` in `isoforms.results` is calculated.
Does it represent column `FPKM` in `isoforms.results` divided by the same column in `genes.results`?

Thank you,
Minghao

**Comment by cndewey** [comment]
Hi Minghao,

It is the the relative abundance of the isoform (TPM) divided by the relative abundance of its gene (TPM).  Within a sample, FPKM is proportional to TPM, so your interpretation is correct as well.

Best,
Colin
