### ISSUE TITLE
Issue when calculating expression with RSEM 1.3.3

### ISSUE THREAD

**Issue by necrosnake91** [deweylab/RSEM#155]
Hi RSEM experts,

Currently I'm trying to estimate the abundance of transcriptomic data by running:

```
for i in ${1..10}; do
#Generate the list with the names of the bam files
samples="s0${i}_Aligned.toTranscriptome.out.bam"
#Calculate expression
rsem-calculate-expression --paired-end \
                          --bam \
                          -p 8 \
                          ../STAR_output/$samples \
                          ../RSEM_output/reference \
                          ../RSEM_output/s0$i
```
Some samples succeeded. However, other samples failed and had the next error message:

```
"rsem-run-em ../RSEM_output/reference 3 ../RSEM_output/s02 ../RSEM_output/s02.temp/s02 ../RSEM_output/s02.stat/s02 -p 8 -b ../STAR_output/s02_Aligned.toTranscriptome.out.bam 0" failed! Plase check if you provide correct parameters/options for the pipeline!
```
When I ran the code only selecting those failed samples, only two of six succeeded. 
Trying to figure out what was going on, I:

- Created again the bam files of failed samples using STAR
- Ran the code for every single sample

However, I'm still having the same trouble on those samples
I'm looking for your help!

Best regards

**Comment by necrosnake91** [comment]
After searching the main reasons of this error message, I fixed the issue. Such failed samples had a lot of reads and thus the core was dumped. Increasing the number of threads solved the issue.

**Comment by akh8zm** [comment]
Here to +1 your approach in case anyone else comes googling for an answer. I was running RSEM 1.3.2 on pre-made STAR alignments (the `Aligned.toTranscriptome.out.bam` file), containing paired end reads for 10 mouse samples. The RSEM index would create successfully, but running `rsem-calculate-expression` would fail after about 2 hours with the error message `"Number of alignable reads does not match!"` and an error in `rsem-run-em`, `"Plase check if you provide correct parameters/options for the pipeline!"` Increasing the number of threads from 8 to 16 solved the issue.
