### ISSUE TITLE
STAR errors out asking for a specific parameter

### ISSUE THREAD

**Issue by RamRS** [deweylab/RSEM#163]
Hi,

I'm running `rsem-calculate-expression` like so:

```sh
/path/to/rsem-calculate-expression \
        --paired-end \
        --star \
        --star-path /path/to/STAR \
        --keep-intermediate-files \
        --star-gzipped-read-file \
        {input.fq1} {input.fq2} \
        --star-output-genome-bam \
        /path/to/rsem/prepared/hg38 \
        sample_name.
```

But in a few samples, I run into this error:

```
EXITING because of fatal error: buffer size for SJ output is too small
Solution: increase input parameter --limitOutSJcollapsed
```

I'd really like to pass this parameter on to STAR without having to align with STAR separately. Is that possible?

Also, these samples worked fine a few months ago, and comparing the commands and versions, the only difference is that those commands used `-p 8`. Does that make a difference?

**Comment by pliu55** [comment]
Hi @RamRS,

It is possible to add `--limitOutSJcollapse` parameter.  You can manually add it in [rsem-calculate-expression's line 490](https://github.com/deweylab/RSEM/blob/e4dda70e90fb5eb9b831306f1c381f8bbf71ef0e/rsem-calculate-expression#L490) using:

```
" --limitOutSJcollapse your_new_parameter ".
```

where `your_new_parameter` represents the parameter you would like to use.  

Hope it is helpful.

Best,
Peng

**Comment by RamRS** [comment]
Thank you - I will add it to the source file right now. Do you think it would be possible to allow passthrough flags in a future version of RSEM?

**Comment by pliu55** [comment]
Thanks for the suggestion.  I will keep this feature request in mind and hopefully add it in a future release.
