### ISSUE TITLE
expression level of some genes is different when watching BAM file

### ISSUE THREAD

**Issue by dahun73** [deweylab/RSEM#183]
Hello, 

I'm curious whether RSEM can calculate expression considering strandness of RNA.

The reason why I'm curious is that some genes are different between quantified expression and BAM file.

For example, the expression of 'GNB3' gene is more than 10. In BAM file, however, mapped reads have small number.

![image](https://user-images.githubusercontent.com/52641420/157600438-d5317bf5-648b-48ba-acb0-fa1d8882f976.png)

As you can see, the strand of 'GNB3' is positive. So, we could expect that expression level of this gene is low number. However, expression level(such as FPKM, TPM) is larger number than I expected.

Also, in minus strand, there are many reads more than plus strand. So, I'm curious about RSEM can consider strandness of gene when calculating expression(Basically, I think it must be able to consider strandness.)

Thank you in advance!

**Comment by pliu55** [comment]
@dahun73 

RSEM can calculate expression considering strandness of RNA.  Please check out the `--strandedness` option in [rsem-calculate-expression](https://deweylab.github.io/RSEM/rsem-calculate-expression.html#BASIC-OPTIONS)

**Comment by dahun73** [comment]
Thank you, @pliu55. I found it!
