### ISSUE TITLE
RSEM deal with multimapping?

### ISSUE THREAD

**Issue by marwa38** [deweylab/RSEM#206]
Could you please answer my below question I received from a reviewer?
Include information on how the RNA-Seq aligner dealt with multimapping reads (did it output all possible alignment locations, or just a single one per read?)

Thanks 
M

**Comment by IvonaPYF** [comment]
Might be late for the original author, but if anyone has similar concerns, I would recommend reading the following review article: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7330433/ especially paying attention to Table 1  and Fig. 3. You will see how different aligners work and what strategies they use.
