### ISSUE TITLE
Using STAR BAMs from genomic alignment

### ISSUE THREAD

**Issue by charlesdavid** [deweylab/RSEM#210]
Wanted to try this program with my existing alignment files to a genome. Ran the preprocessing and got all the indices, but looks like this code can not handle what I want to do. Could someone tell me how to proceed or that it is not possible? Thanks. (All most all of our work uses genomic alignments with STAR. So need to know if our workflows are compatible with RSEM)    :-)

**Comment by pliu55** [comment]
@charlesdavid RSEM's `rsem-calculate-expression` has an option `--bam` that can use STAR BAMs. Note that, this BAM needs to be alignment on transcriptome, not genome.

**Comment by charlesdavid** [comment]
Right. So NOT compatible with genomic alignments. Oh well.
