### ISSUE TITLE
cleaned.fq.gz: command not found

### ISSUE THREAD

**Issue by albustruong** [deweylab/RSEM#213]
Hi,

I'm trying to test run mapping a paired-end read of 1 sample of mine to rsem-indexing reference (Please see photos for where I gather and prepare them for mapping.

I use this script:
#!/bin/bash
rsem-calculate-expression \
--bowtie2 --bowtie2-path /usr/bin --phred33-quals \
--paired-end \
--p 6 --output-genome-bam \
--sort-bam-by-coordinates /
sub1-Ca13mCh-LGC9389_L1_1_cleaned.fq.gz \
sub1-Ca13mCh-LGC9389_L1_2_cleaned.fq.gz \
ref \
sub1-Ca13mCh-LGC9389_L1_paired_end_quals \
2>&1 | tee sub1-Ca13mCh-LGC9389_L1_log.txt

Error report is:
./mapping_sample.sh: line 8: sub1-Ca13mCh-LGC9389_L1_1_cleaned.fq.gz: command not found

Please help me. Thanks.

![image](https://github.com/deweylab/RSEM/assets/22863226/9aef1a8a-c008-43c7-95e4-be8b824df65f)
![image](https://github.com/deweylab/RSEM/assets/22863226/e60188a9-da02-4702-a78f-7c101570f92a)

**Comment by cndewey** [comment]
That error message suggests that "sub1-Ca13mCh-LGC9389_L1_1_cleaned.fq.gz" is at the beginning of a command line.  If you look at the line above that filename, you'll see that you used a forward slash "/" instead of a backslash "\\".  You need to use a backslash instead for line continuation.

**Comment by albustruong** [comment]
Hi @cndewey ,

Thanks a lot for your help. I corrected the forward slash "/" to a backlash "\":

#!/bin/bash
rsem-calculate-expression \
--bowtie2 --bowtie2-path /usr/bin --phred33-quals \
--paired-end \
--p 6 --output-genome-bam \
--sort-bam-by-coordinates \
sub1-Ca13mCh-LGC9389_L1_1_cleaned.fq.gz \
sub1-Ca13mCh-LGC9389_L1_2_cleaned.fq.gz \
ref \
sub1-Ca13mCh-LGC9389_L1_paired_end_quals \
2>&1 | tee sub1-Ca13mCh-LGC9389_L1_log.txt

and the error is gone. However, I got another error:

Unknown option: sort-bam-by-coordinates

What should I do?

**Comment by cndewey** [comment]
That error means you have given an option (sort-bam-by-coordinates) to rsem-calculate-expression that it does not recognize.  Please give the [manual](https://deweylab.github.io/RSEM/rsem-calculate-expression.html) a careful read.  The correct option is "--sort-bam-by-coordinate".
