### ISSUE TITLE
Links to specific help document pages broken

### ISSUE THREAD

**Issue by thomasyu888** [deweylab/RSEM#25]
Example: https://github.com/deweylab/RSEM/blob/master/rsem-prepare-reference.html

**Comment by bli25wisc** [comment]
Hi @thomasyu888, thanks for pointing this out. In fact, this is expected. If you want to access the help document, please click the links from this site: http://deweylab.github.io/RSEM/README.html

**Comment by thomasyu888** [comment]
Thanks! I will take a look.
