### ISSUE TITLE
`rsem-run-ebseq` is not installed by `make install`

### ISSUE THREAD

**Issue by wass80** [deweylab/RSEM#26]
Hello.

```
git clone https://github.com/deweylab/RSEM/ 
make && make ebseq && mkdir ../bin && make install DESTDIR=../bin
```
The commands related to EBSeq are not installed to `../bin`.
I want that `make install` installs`rsem-run-ebseq` .

Thanks.

**Comment by bli25wisc** [comment]
Hi @wass80 , 

Thanks for reporting this to us. Unfortunately, because EBSeq is installed via R, currently we do not support make install for EBSeq related scripts.

Hope it helps,
Bo

**Comment by wass80** [comment]
Thanks. I will use these script directly.
