### ISSUE TITLE
Strand Specific Mapping Performs Poorly

### ISSUE THREAD

**Issue by DarioS** [deweylab/RSEM#34]
I use the `--paired-end` and `--strand-specific` options to map to the GENCODE Genes 25 transcriptome with Bowtie.

For `--forward-prob 0` I get 2.79 % of reads mapped, for `--forward-prob 1` I **again** get 2.79 % and when all of the strand specific options are left out of the command, I get 79.99 % mapped reads.

I have also mapped with STAR to the genome, and the mapping percentage is high and the reads are clearly strand-specific when viewed in IGV and coloured by strand of the first read in the pair. Why is the mapping percentage so low with the stand-specific approach to RSEM and Bowtie ? Also, using `--forward-prob 0` and `--forward-prob 1` should not produce identical mapping percentages. Are they being ignored in the code ?

I am using version 1.2.31.

**Comment by cndewey** [comment]
Hi,

When you specify the --forward-prob option to RSEM are you also using the --strand-specific option?  If so, try omitting the --strand-specific option, which I believe forces --forward-prob 1.

In summary, try just --forward-prob 0 without the --strand-specific option.

Colin

On Sep 23, 2016, at 2:00 AM, DarioS <notifications@github.com<mailto:notifications@github.com>> wrote:


I use the --paired-end and --strand-specific options to map to the GENCODE Genes 25 transcriptome with Bowtie.

For --forward-prob 0 I get 2.79 % of reads mapped, for --forward-prob 1 I again get 2.79 % and when all of the strand specific options are left out of the command, I get 79.99 % mapped reads.

I have also mapped with STAR to the genome, and the mapping percentage is high and the reads are clearly strand-specific when viewed in IGV and coloured by strand of the first read in the pair. Why is the mapping percentage so low with the stand-specific approach to RSEM and Bowtie ? Also, using --forward-prob 0 and --forward-prob 1 should not produce identical mapping percentages. Are they being ignored in the code ?

I am using version 1.2.31.

**Comment by DarioS** [comment]
Thanks; the workaround is sufficient. But, it's a bit unexpected from an end user's perspective that `--strand-specific` dominates the setting of `--forward-prob`. Perhaps this could be changed, or at least explicitly documented. If  `--forward-prob` was deprecated and `--strand-specific` was replaced by `--strandedness` and had `none`, `forward`, and `reverse` as the three acceptable values, it would be unambiguous and concise. It's also currently unlcear what happens if the user provide a value like `0.30` for `--forward-prob`, which is meaningless.

**Comment by bli25wisc** [comment]
Hi @DarioS, thanks for your suggestions!  I have added --strandedness 'none/forward/reverse' option and deprecated --strand-specific and --forward-prob options. This will be reflected in the next release of RSEM. 

Thanks,
Bo
