### ISSUE TITLE
Prepare reference error

### ISSUE THREAD

**Issue by abdelrahmanhosny** [deweylab/RSEM#38]
I want to use RSEM on human genome using RefSeq gene annotations.
I downloaded the browser from UCSC browser.

I run the following command
rsem-prepare-reference --gtf annotations/hg19-annotations-refseq.gtf \
genome.fa \
ref/human_gencode

I get the following error:
rsem-extract-reference-transcripts ref/human_gencode 0 annotations/hg19-annotations-refseq.gtf 0 genome.fa
Parsed 200000 lines
Parsed 400000 lines
Parsed 600000 lines
Parsed 800000 lines
Parsed 1000000 lines
According to the GTF file given, a transcript has exons on multiple chromosomes!
"rsem-extract-reference-transcripts ref/human_gencode 0 annotations/hg19-annotations-refseq.gtf 0 genome.fa" failed! Plase check if you provide correct parameters/options for the pipeline!

How can I use RefSeq genes with RSEM?

**Comment by bli25wisc** [comment]
Hi @abdelrahmanhosny, the problem here is that NM numbers are not unique for transcripts. To build RefSeq references, please refer to http://deweylab.github.io/RSEM/README.html#built

Hope it helps,
Bo
