### ISSUE TITLE
Please clarify license of IDR source code in pRSEM directory

### ISSUE THREAD

**Issue by mr-c** [deweylab/RSEM#41]
Thank you for releasing RSEM & pRSEM as free software!

However there are some problems with the third-party source code included (and in some cases, modified) inside the pRSEM directory:

For example, the [version of idr that was modified](https://github.com/deweylab/RSEM/blob/master/pRSEM/idrCode/batch-consistency-analysis.r) appears to have been never released under any license I can find, as https://sites.google.com/site/anshulkundaje/projects/idr/idrCode.tar.gz?attredirects=0 has not licensing information nor does https://sites.google.com/site/anshulkundaje/projects/idr

Version 1.0, 1.1, and 1.11 of IDR is licensed LGPL (>= 2.0), but the code doesn't appear to be the version adapted here. The version 1.2 on cran is licensed GPL-2+ https://cran.r-project.org/web/packages/idr/  and version 2.0+ on Github are also licensed GPL-2+

Without proof that the 2010 version of IDR was released under _any_ free or open source license means that Debian cannot distribute pRSEM. Without a license it also means that _you_ can not distribute that code or your modifications.
- [ ] Can you secure a license to the version of IDR used?
- [ ] Can you switch to the [released and maintained version of IDR](https://github.com/nboley/idr)? Debian, and others, would [appreciate that](https://wiki.debian.org/UpstreamGuide#No_inclusion_of_third_party_code).

**Comment by pliu55** [comment]
Hi Michael,

Thanks for bringing up this issue. The IDR code is a slightly modified version from <https://sites.google.com/site/anshulkundaje/projects/idr>, which is supposedly under MIT license. I am wondering if we ask the author of <https://sites.google.com/site/anshulkundaje/projects/idr> to add a MIT license to <https://sites.google.com/site/anshulkundaje/projects/idr>, would that solve the issue here? If so, I will contact the author about it.

**Comment by mr-c** [comment]
Thank you @pliu55 for the response. Yep, that would suffice, though it would be better to upgrade to the latest IDR release from https://github.com/nboley/idr

**Comment by pliu55** [comment]
The author of IDR added GPLv2 license. Please check it out: <https://sites.google.com/site/anshulkundaje/projects/idr/#TOC-Code-for-IDR-Analysis>.

**Comment by DieTANG** [comment]
Hello, I can't find the rsem-parse-alignments file in RSEM. Is this not included in RSEM?

**Comment by bli25wisc** [comment]
@DieTANG You should first compile RSEM by typing 'make' and then 'rsem-parse-alignments' will appear.
