### ISSUE TITLE
RSEM cannot calculate credibility intervals on Debian 7.8

### ISSUE THREAD

**Issue by emi80** [deweylab/RSEM#45]
Hi,
I am using RSEM 1.2.21. When running it on a Debian Wheezy 7.8 installation 
it looks like the ci bounds could not be computed. I get the following output in the `.genes.results` file:

```
FBgn0002521	FBtr0089204,FBtr0089205	2159.00	1976.37	14.00	17047.35	8586.31	14.00	0.00	12983.33	6862.00	6937.52	19666.4	-1e+30	1e+30
```

When running the same command with the same data on Debian Jessie 8.6 or Centos 6.7 it seems to work:

```
FBgn0002521	FBtr0089204,FBtr0089205	2159.00	1976.37	14.00	17047.35	8586.31	14.00	0.00	12983.33	6862.00	6937.52	19666.4	3647.78	10230.2
```

I tried with different versions of RSEM but the problems still remains.

Do you have any idea about what this could be related to?

Thanks

**Comment by bli25wisc** [comment]
@emi80 Sorry I'm not sure why it happens... Have you tried RSEM v 1.3.0?
