### ISSUE TITLE
problem installing under cygwin

### ISSUE THREAD

**Issue by jchenpku** [deweylab/RSEM#46]
when I comiled the source under cygwin, I met the following error:
anything missing?
{ RSEM-master }  » make cygwin=true                             /cygdrive/g/NGS/bin/RSEM-master 2
g++  -pthread -o rsem-parse-alignments parseIt.o samtools-1.3/htslib-1.3/libhts.a  -lz
parseIt.o:parseIt.cpp:(.text+0x256e): undefined reference to `bam_hdr_destroy'
parseIt.o:parseIt.cpp:(.text+0x2576): undefined reference to `hts_close'
parseIt.o:parseIt.cpp:(.text+0x257f): undefined reference to `bam_destroy1'
parseIt.o:parseIt.cpp:(.text+0x26d6): undefined reference to `sam_read1'
parseIt.o:parseIt.cpp:(.text+0x29bb): undefined reference to `bam_aux_get'
parseIt.o:parseIt.cpp:(.text+0x29cc): undefined reference to `bam_aux2i'
parseIt.o:parseIt.cpp:(.text+0x2c68): undefined reference to `sam_read1'
parseIt.o:parseIt.cpp:(.text+0x2eeb): undefined reference to `bam_aux_get'
parseIt.o:parseIt.cpp:(.text+0x2efc): undefined reference to `bam_aux2i'
parseIt.o:parseIt.cpp:(.text+0x317d): undefined reference to `sam_read1'
parseIt.o:parseIt.cpp:(.text+0x3195): undefined reference to `sam_read1'
parseIt.o:parseIt.cpp:(.text+0x37fb): undefined reference to `bam_aux_get'
parseIt.o:parseIt.cpp:(.text+0x380c): undefined reference to `bam_aux2i'
parseIt.o:parseIt.cpp:(.text+0x38bb): undefined reference to `bam_aux_get'
parseIt.o:parseIt.cpp:(.text+0x38c8): undefined reference to `bam_aux2i'
parseIt.o:parseIt.cpp:(.text+0x3d68): undefined reference to `sam_read1'
parseIt.o:parseIt.cpp:(.text+0x3d80): undefined reference to `sam_read1'
parseIt.o:parseIt.cpp:(.text+0x43cb): undefined reference to `bam_aux_get'
parseIt.o:parseIt.cpp:(.text+0x43dc): undefined reference to `bam_aux2i'
parseIt.o:parseIt.cpp:(.text+0x455b): undefined reference to `bam_aux_get'
parseIt.o:parseIt.cpp:(.text+0x4568): undefined reference to `bam_aux2i'
parseIt.o:parseIt.cpp:(.text+0x678d): undefined reference to `hts_open'
parseIt.o:parseIt.cpp:(.text+0x67a5): undefined reference to `hts_set_fai_filename'
parseIt.o:parseIt.cpp:(.text+0x67ad): undefined reference to `sam_hdr_read'
parseIt.o:parseIt.cpp:(.text+0x67d5): undefined reference to `bam_init1'
parseIt.o:parseIt.cpp:(.text+0x67de): undefined reference to `bam_init1'
parseIt.o:parseIt.cpp:(.text+0x258e): undefined reference to `bam_destroy1'
collect2.exe: error: ld returned 1 exit status
Makefile:81: recipe for target 'rsem-parse-alignments' failed
make: *** [rsem-parse-alignments] Error 1

**Comment by bli25wisc** [comment]
@jchenpku , Sorry for my late reply. Have you built "samtools-1.3/htslib-1.3/libhts.a" under Cygwin? Or you have it ready before you typed 'make'?

**Comment by jchenpku** [comment]
thank you for your reply. I got the error when using babun and then I found that there might be some problem with my babun so I switched to the original cygwin. Now I have successfully built RSEM.

**Comment by bli25wisc** [comment]
@jchenpku  Great to hear!
