### ISSUE TITLE
Transcript-to-gene-map and NgVector

### ISSUE THREAD

**Issue by standage** [deweylab/RSEM#5]
The `rsem-prepare-reference` script allows you to specify the mapping of transcripts to genes. The `rsem-run-ebseq` script utilizes this mapping information to do an isoform-level gene expression analysis, but requires you to provide this information as an "ngvector" file. I looked at the files generated by the `rsem-prepare-reference` script, but none of them look like an ngvector file.

I see the documentation for the `rsem-generate-ngvector` script, but it seems to compute its own mapping rather than use the one provided with the `--transcript-to-gene-map` option in `rsem-prepare-reference`.

Am I missing something? If I already have the mapping of transcripts to genes, how do I provide this information to `rsem-run-ebseq`?

**Comment by bli25wisc** [comment]
RSEM arranges transcripts by first its parent gene's name and then its name. *.grp file describes a cumulative sum of number of transcripts for each gene. We can use this information to determine the number of transcripts belonging to each gene and their start and end positions in the reference.
