### ISSUE TITLE
mask/ignore rRNA when rsem-calculate-expression, but not rsem-prepare-reference

### ISSUE THREAD

**Issue by wangyugui** [deweylab/RSEM#53]
Is it posssible to mask/ignore rRNA when rsem-calculate-expression, but not rsem-prepare-reference.

If we add rRNA to ref, we can get the rRNA rate from the result bam file ,
and  Less false positive when mapping.

**Comment by bli25wisc** [comment]
@wangyugui , in that case, you could just add rRNA in your reference. Then if you do not want rRNAs, you could remove them from RSEM result files and renormalize the expression of rest isoforms to be 10^6.

Hope it helps,
Bo

**Comment by wangyugui** [comment]
Is there a tool to renormalize the expression of rest isoforms?

**Comment by bli25wisc** [comment]
@wangyugui , no. But it is very simple, you can write a script yourself: summing all TPMs for transcripts of interest and then making this sum into 10^6.

**Comment by wangyugui** [comment]
Thanks a lot for your answer.
