### ISSUE TITLE
process-chipseq.R Error in rbindlist(bplapply(files, guessFqEncodingByFile))

### ISSUE THREAD

**Issue by crazyhottommy** [deweylab/RSEM#58]
I was running pRSEM https://github.com/deweylab/RSEM/issues/54 , everything was fine until this step:

```
Error in rbindlist(bplapply(files, guessFqEncodingByFile)) :
  attempt to set an attribute on NULL
Calls: main -> <Anonymous> -> rbindlist
```

I grep and saw this code is from the `process-Chipseq.R`, any guess what is possibly wrong here?
Thanks,
Tommy

**Comment by pliu55** [comment]
@crazyhottommy 

Did you experience the same issue when running pRSEM's demo? 

This code is using the [ShortRead](https://bioconductor.org/packages/release/bioc/html/ShortRead.html) library to guess your ChIP-seq FASTQ's encoding, e.g. phred33, phred64, etc. We utilize the [BiocParallel](https://bioconductor.org/packages/devel/bioc/html/BiocParallel.html) to parallel this process. Could you try the `bplapply` function on your system and see if there's any issue with it?

**Comment by crazyhottommy** [comment]
I installed it and `bplapply` works, but still same error. I decide to use the peak mode to get away processing the raw ChIP-seq data, so for the `-chipseq-target-peak-file` the input is in narrowpeak format, if I only have peaks with 3 columns, chr, start, end. can I use it? does p-RSEM use other columns (e.g. score, pvalues) ?

Thanks!

**Comment by pliu55** [comment]
@crazyhottommy 

pRSEM only use _chr_, _start_, and _end_, and does not use info from the other columns, but pRSEM assume the input peak file is in gzipped and have 10 columns (as following the narrowpeak format). So please:
- add 7 columns of `NA` (or whatever info you prefer) to your peak file
- gzip it

Just for the reference, [line 513-516 in process-rnaseq.R](https://github.com/deweylab/RSEM/blob/master/pRSEM/process-rnaseq.R) should be the code that reads peak file and I paste them below:

```
    data.table(read.table(gzfile(fchipseq_peaks), header=F, sep="\t",
                          colClasses=c('character', 'numeric',
                                       'numeric', rep('NULL', 7))))

```

**Comment by crazyhottommy** [comment]
thanks! this is helpful.
