### ISSUE TITLE
Incorrect Version Number Displayed

### ISSUE THREAD

**Issue by DarioS** [deweylab/RSEM#64]
I was confused why it seemed I wasn't using 1.3.0, but then realised that the version number seems to not have been updated in the software.

```
$ /tmp/RSEM-1.3.0/rsem-calculate-expression --version
Current version: RSEM v1.2.31
```

**Comment by karl616** [comment]
I would also appreciate having this issue resolved.

**Comment by bli25wisc** [comment]
@DarioS @karl616  Fixed.

**Comment by DarioS** [comment]
But now the `beta` software branch has a smaller version number than `master`.
