### ISSUE TITLE
RSEM rsem-parse-alignments problem

### ISSUE THREAD

**Issue by reedliu** [deweylab/RSEM#83]
Hi RSEM expert, 
Recently I met a problem with the RSEM .
_**The errors are as follows:**_
**rsem-parse-alignments /home/u1239/workspace/rna-seq/Quantification/../Assembly/trinity_out_dir/Trinity.fasta.RSEM RSEM.temp/RSEM RSEM.stat/RSEM bowtie2.bam 3 -tag XM
open: No such file or directory
Cannot open 3! It may not exist.
"rsem-parse-alignments /home/u1239/workspace/rna-seq/Quantification/../Assembly/trinity_out_dir/Trinity.fasta.RSEM RSEM.temp/RSEM RSEM.stat/RSEM bowtie2.bam 3 -tag XM" failed! Plase check if you provide correct parameters/options for the pipeline!
Error, cmd: rsem-calculate-expression  --paired-end   -p 24    --no-bam-output --bam bowtie2.bam /home/u1239/workspace/rna-seq/Quantification/../Assembly/trinity_out_dir/Trinity.fasta.RSEM RSEM  died with ret: 65280 at /home/u1239/Biosoft/Trinity-v2.5.1/util/align_and_estimate_abundance.pl line 778.**

**Comment by bli25wisc** [comment]
@reedliu , that's weird. Could you update RSEM to v1.3.0 and try it again?

**Comment by lybird300** [comment]
Hi there,

I'm having the same problem and my RSEM version is 1.3.1. I was following the [ENCODE long rna-seq pipeline](https://github.com/ENCODE-DCC/long-rna-seq-pipeline/blob/master/DAC/STAR_RSEM.sh) and using RSEM to calculate transcript expression from STAR transcriptomic bam. 

In the log file, it says,

rsem-parse-alignments .../encode_longRnaseq/RSEM_index_hg19/RSEMref Quant.temp/Quant Quant.stat/Quant Aligned.toTranscriptome.out.bam 3 -tag XM
**Done!**

rsem-build-read-index 32 1 0 Quant.temp/Quant_alignable_1.fq Quant.temp/Quant_alignable_2.fq
Cannot open Quant.temp/Quant_alignable_1.fq! It may not exist.

I checked and the Quant.temp folder was indeed empty, but it seems rsem-parse-alignments finished.

Could you please help me out? I can send you the bam file if it helps. Thanks!
