### ISSUE TITLE
rsem-prepare-reference

### ISSUE THREAD

**Issue by fcamus** [deweylab/RSEM#84]
Hi there, 

I am trying to build a reference with the D.melanogaster genome. I downloaded the fasta and .gtf files from the latest release in flybase (ftp://ftp.flybase.net/genomes/Drosophila_melanogaster/dmel_r6.19_FB2017_06/) and got this error: 

The GTF file might be corrupted!
Stop at line : 3R	FlyBase	mRNA	21360390	21377399	.	gene_id "FBgn0002781"; gene_symbol "mod(mdg4)"; transcript_id "FBtr0084079"; transcript_symbol "mod(mdg4)-RT";
Error Message: Strand is neither '+' nor '-'!

**Comment by fcamus** [comment]
Just an update - I downloaded the ENSEMBL GTF file and genome, and it worked. Don't know why Flybase files dont work though...

**Comment by bli25wisc** [comment]
Hi @fcamus, this suggests that your GTF file is corrupted. There should be a strand information (either '+' or '-') between '.' and 'gene_id'. 

Hope it helps,
Bo
