### ISSUE TITLE
Strandedness - automatic inference

### ISSUE THREAD

**Issue by uros-sipetic** [deweylab/RSEM#85]
Hi, currently the user has to specify the '--strandedness' option. However, nowadays it seems that people get FASTQ files and run different analyses with them, without knowing much about them (like the library type, for example). 
Is it possible to automatically infer the strandedness of input reads, similar to what the Salmon tool already does https://salmon.readthedocs.io/en/latest/salmon.html#what-s-this-libtype ?

**Comment by bli25wisc** [comment]
@uros-sipetic , sure thing. I'll include this option in future releases. Thanks for the suggestion!

**Comment by uros-sb** [comment]
Hey @bli25wisc was this ever added to any RSEM release since this issue?
