### ISSUE TITLE
rsem-prepare-reference with a fasta transcript 

### ISSUE THREAD

**Issue by geparada** [deweylab/RSEM#87]
Hello deweylab!

I'm having an issue when I try to prepare a reference from a gene annotated transcripts in a fasta file. For instance here I just have one transcript as a test (named test.fa)

`>ENSMUST00000072578.7
GCCAATCCCATCATCCCTGACCAACTGTCACCCTCCCGAGCTGCGCAAGCTGCGTCGGTCTGTGATACCGCTACTGGCACGAGCCCTGGGCAGAGGGTCCGGCGGAGGGATCCGCAGAGGCTAAGGTCTCAGAAGAAGAGTCAGCTACTGCGGCAGCACAAAAAAGGCGGCTACAGGGTGATGCGACAACCGATGTGAAGACAGATACAGTGCCCACGGTGGCTGGCCCGGAAGCTGAGTGGGCCTCGGCCCTCAGCGCATTCTGCCAGGGCCAGGCCAGAACTGCCTGCCTCCTCTTCTGCGGCTGATCCAAAACCAGCAAGGCAGCCCCAGGCCCTCGGTGCCTGCCTCCTTCCACCTGGGGCCTACCAAGACAGCCTTCCACCATGGCTCTGAAGAGAATCCACAAGGAACTGAACGACCTGGCCCAGGATCCCCCAGCACAGTGTTCAGCAGGTCCTGTCGGGGAAGATATGTTTCACTGGCAAGCTACAATCATGGGGCCAAATGATAGTCCCTATCAGGGCGGAGCATTTTTCTTGACAATTGATTTCCCAACAGAGTACCCCTTCAAACCACCTAAGGTTGAATTTACAACAAGAATTTATCATCCAAATGTTAACAGTAACGGCAGTATTTGTCTTGATATTCTTCGGTCACAGTGGTCTCCAGCACTAACTATTTCCAAAGTACTTTTGTCCATCAGTTCTCTGTTGTGTGACCCCAATCCAGATGATCCCTTAGTGCCTGAGATTGCTCAGATCTACAAAACAGATAGAGACAAGTACAACAGAACAGCTCGGGAATGGACTCAGAAATATGCGATGTGACTAAAGAGAATACTGGATATCCTCTACAAATAAAAGCTAGGGGAACTCTGAAAGAGAAGTTCTTTTGATTCCCACCGGACTGTTTCCCATGAACCCACGCCCACGCTGTACCTGCCTCATCCTCCCTGGTGCACCGTCTTCACCTGATACAGTACCGCTGCATGTTGCACGCACCAGAAATACTGTACCAACACTGTCTCCTAGCAGACGAGCGTTCTCCAGGCATAACCTGGATGTGAGATTAAAAGTTTTCCTTATTGACTTAAATCTGGATAACCACAAGGTGTGAGGGTGGTGGGTACACAATACTGCTCAGAAGGGGTAAAGGTCCCCCAATCTATAAGAGACAATGAGATTGCTTTTAAGTGGAAGCCATTTAAATTTAAATTTTTTTAATTTATA`

But when I try to run `rsem-prepare-reference test.fa test`, I get this error:

`rsem-synthesis-reference-transcripts test 0 0 test.fa
Sequence ENSMUST00000072578.7 contains an unknown letter (ASCII code 13) at 0-based position 1677!
"rsem-synthesis-reference-transcripts test 0 0 test.fa" failed! Plase check if you provide correct parameters/options for the pipeline!`

Also other people is having the same error:

https://groups.google.com/forum/#!topic/rsem-users/sOjD9Kh8vrc

Are we doing something wrong? 

Thanks for your help!

**Comment by bli25wisc** [comment]
@geparada, your file ends with '\r\n' instead of '\n'. It should work if you remove '\r'.
